### ISSUE TITLE
Can't avoid marshalling a request body

### ISSUE THREAD

**Issue by adreed-msft** [Azure/go-autorest#495]
It's a known issue that AutoRest can't switch between marshalling XML and JSON. The workaround for this within our team has been to just treat the body as a string, and then to parse it ourselves later.

The Go generator will not cooperate with that hack. I can get it to treat certain properties as strings, and not as their original object types, but those strings are forced to run through `xml.Marshal` regardless.

For reference, here's the directive being used to achieve this, alongside the generator settings:

Settings:
``` yaml
input-file: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/storage-dataplane-preview/specification/storage/data-plane/Microsoft.FileStorage/preview/2019-02-02/file.json
go: true
output-folder: Go_FileStorage
namespace: azfile
go-export-clients: false
enable-xml: true
file-prefix: zz_generated_
```

Directive:
```yaml
directive:
- from: swagger-document
  where: $["x-ms-paths"]["/{shareName}?restype=share&comp=filepermission"]
  transform: >
    delete $.put.consumes;
    $.put.responses["201"]["x-az-response-name"] = "PermissionInfo";
    delete $.get.produces;
- from: swagger-document
  where: $.parameters.SharePermission
  transform: >
    $.schema = { "type": "string" };
    $["x-ms-client-name"] = "sharePermissionJson";
- from: swagger-document
  where: $.definitions.SharePermission
  transform: >
    $.type = "string";
    delete $.required;
    delete $.properties;
```

This means that each time we generate the code, we have to modify the generated code to not marshal the string.
